"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-b2h^o*6gx1!^&^6&28b_vq%!9a8$$9^+=r4*)5i*)su@o@_vjp'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'yunho.apps.YunhoConfig',
    'github_oauth.apps.GithubOauthConfig',
    'google_oauth.apps.GoogleOauthConfig',
    'user.apps.UserConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': str(BASE_DIR / 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Seoul' #default: 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


#Google Oauth Section
GOOGLE_CLIENT_ID = '1008108087440-k91al7rsvpvoenjb8vt5pjqkuke9k9u9.apps.googleusercontent.com'
GOOGLE_CLIENT_SECRET_PASSWORD = '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'
GOOGLE_TOKEN_API = 'https://oauth2.googleapis.com/token'
GOOGLE_ENDPOINT = 'https://accounts.google.com/o/oauth2/v2/auth' #인증서버
GOOGLE_SCOPE = 'https://www.googleapis.com/auth/userinfo.email ' + 'https://www.googleapis.com/auth/userinfo.profile ' + 'openid'
GOOGLE_REDIRECT_URI = 'http://127.0.0.1:8000/yunho/login/google/callback'
GOOGLE_REDIRECT_URI_GOORM = 'https://opensource-egynk.run.goorm.site/yunho/login/google/callback'

#Github Oauth Section
GITHUB_CLIENT_ID = '71d3e522408753248fd2'
GITHUB_CLIENT_SECRET_PASSWORD = '9ceab046c5a0a48085ecee150e7c06ac941e936a'
GITHUB_TOKEN_API = 'https://github.com/login/oauth/access_token'
GITHUB_ENDPOINT = 'https://github.com/login/oauth/authorize'
GITHUB_SCOPE = 'repo ' + 'user'
GITHUB_REDIRECT_URI = 'http://127.0.0.1:8000/yunho/login/github/callback'
GITHUB_REDIRECT_URI_GOORM = 'https://opensource-egynk.run.goorm.site/yunho/login/github/callback'

#session Section
SESSION_COOKIE_AGE = 60 #세션 만료 시간
SESSION_SAVE_EVERY_REQUEST = True #요청시 세션 만료 시간 초기화
SESSION_EXPIRE_AT_BROWSER_CLOSE = True # 브라우저 닫으면 session 없애기
# SESSION_SAVE_EVERY_REQUEST = True # update되면 session바로 반영


#custom user model Section
AUTH_USER_MODEL = 'user.User'

#Authentication backends
AUTHENTICATION_BACKENDS = [
        'django.contrib.auth.backends.ModelBackend',
]